/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // King's Head Industrial Color Palette
        'surface': '#f6f9ff',
        'surface-dim': '#d4dbe2',
        'surface-bright': '#f6f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4fc',
        'surface-container': '#e8eef6',
        'surface-container-high': '#e3e9f1',
        'surface-container-highest': '#dde3eb',
        'on-surface': '#161c22',
        'on-surface-variant': '#444651',
        'inverse-surface': '#2b3137',
        'inverse-on-surface': '#ebf1f9',
        'outline': '#757682',
        'outline-variant': '#c5c5d3',
        'surface-tint': '#4059aa',
        'primary': '#00236f',
        'on-primary': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-primary-container': '#90a8ff',
        'inverse-primary': '#b6c4ff',
        'secondary': '#545f73',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e0f8',
        'on-secondary-container': '#586377',
        'tertiary': '#4b1c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6e2c00',
        'on-tertiary-container': '#f39461',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f6f9ff',
        'on-background': '#161c22',
        'surface-variant': '#dde3eb',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'nav-width': '72px',
        'split-left': '35%',
        'split-right': '65%',
        'base-unit': '8px',
        'gutter': '16px',
        'margin-edge': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      }
    },
  },
  plugins: [],
}
