
/**
 * Produce yield data from chefs-resources.com
 * Yield = usable percentage after normal prep (peeling, trimming, coring).
 * Waste% = 100 - Yield%.
 *
 * Keys are LOWERCASE normalized names for fuzzy matching.
 */

const PRODUCE_YIELDS: Record<string, number> = {
  // --- VEGETABLES ---
  'asparagus': 56,
  'avocado': 72,
  'green beans': 88,
  'beans': 88,
  'runner beans': 88,
  'french beans': 88,
  'lima beans': 39,
  'broad beans': 39,
  'beetroot': 76,
  'beets': 76,
  'bok choy': 67,
  'pak choi': 67,
  'broccoli': 61,
  'broccoli crowns': 95,
  'tenderstem broccoli': 95,
  'brussels sprouts': 74,
  'sprouts': 74,
  'cabbage': 79,
  'red cabbage': 79,
  'green cabbage': 79,
  'savoy cabbage': 79,
  'carrot': 82,
  'carrots': 82,
  'baby carrots': 61,
  'cauliflower': 55,
  'celery': 75,
  'celeriac': 75,
  'chard': 77,
  'swiss chard': 77,
  'cucumber': 95,
  'aubergine': 81,
  'eggplant': 81,
  'endive': 74,
  'chicory': 74,
  'escarole': 74,
  'fennel': 60,
  'garlic': 95,
  'ginger': 80,
  'ginger root': 80,
  'fresh ginger': 80,
  'coriander': 75,
  'cilantro': 75,
  'parsley': 75,
  'mint': 75,
  'tarragon': 75,
  'chives': 90,
  'dill': 75,
  'basil': 75,
  'thyme': 60,
  'rosemary': 60,
  'sage': 75,
  'kale': 74,
  'cavolo nero': 74,
  'leek': 75,
  'leeks': 75,
  'lemongrass': 80,
  'lemon grass': 80,
  'lettuce': 85,
  'romaine': 67,
  'cos lettuce': 67,
  'gem lettuce': 75,
  'little gem': 75,
  'iceberg lettuce': 85,
  'rocket': 92,
  'watercress': 92,
  'mushroom': 97,
  'mushrooms': 97,
  'button mushrooms': 97,
  'chestnut mushrooms': 97,
  'oyster mushrooms': 97,
  'portobello mushroom': 90,
  'portobello mushrooms': 90,
  'shiitake mushrooms': 97,
  'shiitake': 97,
  'wild mushrooms': 90,
  'okra': 78,
  'olive': 95,
  'olives': 95,
  'kalamata olives': 95,
  'onion': 89,
  'onions': 89,
  'red onion': 89,
  'white onion': 89,
  'brown onion': 89,
  'spanish onion': 89,
  'shallot': 89,
  'shallots': 89,
  'spring onion': 92,
  'spring onions': 92,
  'scallion': 70,
  'parsnip': 85,
  'parsnips': 85,
  'peas': 38,
  'garden peas': 38,
  'sugar snap peas': 85,
  'mangetout': 85,
  'snow peas': 85,
  'pepper': 83,
  'peppers': 83,
  'bell pepper': 83,
  'red pepper': 65,
  'green pepper': 65,
  'yellow pepper': 83,
  'orange pepper': 83,
  'chilli': 90,
  'chillies': 90,
  'scotch bonnet': 90,
  'jalapeno': 90,
  'potato': 81,
  'potatoes': 81,
  'new potatoes': 95,
  'jersey royals': 95,
  'maris piper': 81,
  'king edward': 81,
  'sweet potato': 80,
  'sweet potatoes': 80,
  'radish': 63,
  'radishes': 63,
  'daikon': 70,
  'mooli': 70,
  'swede': 85,
  'rutabaga': 85,
  'spinach': 92,
  'baby spinach': 92,
  'squash': 66,
  'butternut squash': 66,
  'acorn squash': 66,
  'courgette': 95,
  'courgettes': 95,
  'zucchini': 95,
  'pumpkin': 66,
  'tomato': 91,
  'tomatoes': 91,
  'cherry tomatoes': 95,
  'sundried tomatoes': 99,
  'sun-dried tomatoes': 99,
  'plum tomatoes': 91,
  'vine tomatoes': 91,
  'turnip': 81,
  'turnips': 81,
  'yam': 81,
  'sweetcorn': 95,
  'corn on the cob': 38,
  'samphire': 90,
  'artichoke': 48,
  'globe artichoke': 48,
  'jerusalem artichoke': 80,

  // --- FRUITS ---
  'apple': 76,
  'apples': 76,
  'cooking apple': 76,
  'bramley apple': 76,
  'banana': 67,
  'bananas': 67,
  'blueberries': 96,
  'blueberry': 96,
  'cantaloupe': 50,
  'melon': 50,
  'honeydew melon': 57,
  'watermelon': 47,
  'cherry': 89,
  'cherries': 89,
  'cranberries': 97,
  'cranberry': 97,
  'grapefruit': 47,
  'grapes': 92,
  'kiwi': 76,
  'kiwi fruit': 76,
  'lime': 30,
  'limes': 30,
  'lemon': 30,
  'lemons': 30,
  'orange': 56,
  'oranges': 56,
  'blood orange': 56,
  'seville orange': 30,
  'peach': 76,
  'peaches': 76,
  'nectarine': 76,
  'nectarines': 76,
  'pear': 78,
  'pears': 78,
  'conference pear': 78,
  'pineapple': 52,
  'plum': 94,
  'plums': 94,
  'damson': 94,
  'rhubarb': 86,
  'strawberry': 89,
  'strawberries': 89,
  'raspberry': 96,
  'raspberries': 96,
  'blackberry': 96,
  'blackberries': 96,
  'mango': 68,
  'passion fruit': 50,
  'pomegranate': 55,
  'fig': 82,
  'figs': 82,
  'apricot': 94,
  'apricots': 94,
  'papaya': 62,
};

/**
 * Look up the yield percentage for a produce item.
 * Uses fuzzy matching: strips common prefixes/suffixes and tries partial matches.
 * Returns the yield % (0-100) or null if no match found.
 */
export const getProduceYield = (name: string): number | null => {
  const lower = name.toLowerCase().trim();

  // Direct match
  if (PRODUCE_YIELDS[lower] !== undefined) return PRODUCE_YIELDS[lower];

  // Strip common prefixes: "fresh", "organic", "baby", "large", "small"
  const stripped = lower
    .replace(/^(fresh|organic|baby|large|small|whole|chopped|diced|sliced|frozen|tinned|canned)\s+/g, '')
    .trim();
  if (PRODUCE_YIELDS[stripped] !== undefined) return PRODUCE_YIELDS[stripped];

  // Strip parenthetical suffixes: "Flour (Plain)" -> "flour"
  const noParens = stripped.replace(/\s*\(.*?\)\s*/g, '').trim();
  if (PRODUCE_YIELDS[noParens] !== undefined) return PRODUCE_YIELDS[noParens];

  // Partial: check if any key is contained in the name or vice versa
  for (const [key, value] of Object.entries(PRODUCE_YIELDS)) {
    if (lower.includes(key) || key.includes(lower)) {
      return value;
    }
  }

  return null;
};
